version: '3.8'
volumes:
  persistent-db:
networks:
  nginx:
services:
  php-fpm:
    container_name: voting_drupal
    restart: always
    build: ./docker
    networks:
      - nginx
    ports:
      - ":9000"
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  nginx:
    image: nginx:latest
    container_name: voting_nginx
    restart: always
    depends_on:
      - db
    networks:
      - nginx
    environment:
      - DB_HOST=db
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/templates:/etc/nginx/templates
    links:
      - db
  db:
    image: mariadb:latest
    container_name: voting_db
    restart: always
    ports:
      - "3306:3306"
    networks:
      - nginx
    environment:
      MYSQL_DATABASE: voting
      MYSQL_USER: voting
      MYSQL_PASSWORD: voting123@
      MYSQL_ROOT_PASSWORD: root
        - persistent-db:/var/lib/mysql:delegated
        - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf